# Generated by Django 5.2.5 on 2026-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
