# Generated by Django 5.2.5 on 2026-04-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='year',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(default='General Consultation', max_length=100),
        ),
    ]
