# Generated by Django 5.2.5 on 2026-04-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_course_remove_appointment_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_notes',
            field=models.TextField(blank=True, default='No specific notes provided.', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, default='No outcome provided.', max_length=255, null=True),
        ),
    ]
